### ISSUE TITLE
Add support for other search engines

### ISSUE THREAD

**Issue by tbejos** [vulgrim/homepage#1]
Just wanted to start with saying thanks! I am a big fan of what you are doing, I just had one suggestion about possibly adding support for other search engines such as duckduckgo for people who like to avoid google. Thanks again!

**Comment by mjanjic01** [comment]
Sure thing. I'll look into it later today.

**Comment by mjanjic01** [comment]
Voila! DuckDuckGo is implemented as an alternate search engine. Check out the latest version on master. Also the README is updated with info on how to configure the engine, at the moment you'll have to change a variable until we implement customizable homepage builds.

**Comment by tbejos** [comment]
Thank you very much!
